language: node_js # Node.js based project
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - yarn build
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out
  github_token: $GITHUB_TOKEN 
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$